-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg74WTCqMtVe5gmWPk
aKN3Sorpdc5JVm2mIw2IgEQtR+ygCgYIKoZIzj0DAQehRANCAATp5ZjeLzHyl8MD
VI0dB9VMRFZf7qAfVBLWimsIrZdORy/+KzDY7hQabkMaI/Q/hJkjtwbUQEH5jskz
PVcRPjox
-----END PRIVATE KEY-----