name: Runner
options:
  bundleIdPrefix: work.zeck
  deploymentTarget:
    iOS: "12.0"

configs:
  Debug:
    type: debug
  Release:
    type: release

targets:
  RunnerTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: RunnerTests
    dependencies:
      - target: Runner
    settings:
      base:
        ENABLE_BITCODE: NO
        SWIFT_VERSION: "5.0"
  Runner:
    type: application
    platform: iOS
    sources:
      - path: Runner
    resources:
      - path: Runner/Assets.xcassets
    info:
      path: Runner/Info.plist
    configFiles:
      Debug: Flutter/Debug.xcconfig
      Release: Flutter/Release.xcconfig
    settings:
      base:
        FLUTTER_ROOT: $(FLUTTER_ROOT)
        FLUTTER_APPLICATION_PATH: $(PROJECT_DIR)/..
        FLUTTER_TARGET: $(PROJECT_DIR)/../lib/main.dart
        SWIFT_VERSION: "5.0"
        ENABLE_BITCODE: NO
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        DEVELOPMENT_TEAM: "297D5XWLQT"
        PRODUCT_BUNDLE_IDENTIFIER: work.zeck.todoList
        SWIFT_OBJC_BRIDGING_HEADER:
          - Runner/Runner-Bridging-Header.h
    configurations:
      Debug:
        FLUTTER_BUILD_MODE: debug
        CODE_SIGN_IDENTITY: iPhone Developer
        PROVISIONING_PROFILE_SPECIFIER: "iOS Development: TodoList (Flutter)"
      Release:
        FLUTTER_BUILD_MODE: release
        CODE_SIGN_IDENTITY: iPhone Distribution
        PROVISIONING_PROFILE_SPECIFIER: "iOS Distribution: TodoList (Flutter)"
    preBuildScripts:
      - path: phase_scripts/run_scripts.sh
        name: Run Script
    postCompileScripts:
      - path: phase_scripts/thin_binary.sh
        name: Thin Binary

schemes:
  - name: Runner
    shared: true
    buildAction:
      targets:
        - Runner
    testAction:
      targets:
        - RunnerTests
      configuration: Debug
    runAction:
      configuration: Debug
    archiveAction:
      configuration: Release