name: Distribute Android .apk
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    workflow_dispatch:

jobs:
  Build-And-Distribute-Android:
    runs-on: ubuntu-latest
    steps:
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

        - uses: actions/checkout@v3
        - name: Install Flutter SDK
          uses: mobiledevops/flutter-sdk-action@v1.0.0
          with:
            flutter-sdk-version: 3.24.3
        - run: cd flutter_application && flutter pub get && flutter build android

        - name: Firebase App Distribution
          uses: hasretsariyer/firebase-app-distribution-github-action@main
          with:
              app_id: ${{ secrets.FIREBASE_APP_ID }}
              firebase_token: ${{ secrets.FIREBASE_TOKEN }}
              app_file: flutter_application/build/outputs/flutter-apk/app-release.apk
              tester_groups: maintainers