name: Distribute iOS .ipa
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: release
        type: choice
        options:
          - release
          - beta
      app:
        description: "Select app to distribute"
        required: true
        type: choice
        options:
          - todo_list

jobs:
  Build-And-Distribute-iOS:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Get current build_number
        id: build_number
        run: echo "build_number=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.12.3'

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version: 3.24.3

      - name: 'Create application.config file'
        run: |
          cd apps/${{ github.event.inputs.app }}/assets/config/
          rm -rf application.config
          echo API_ENDPOINT="${{ secrets.API_ENDPOINT }}" >> application.config
          echo API_KEY=${{ secrets.API_KEY }} >> application.config
          cat application.config

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up .p8 file
        run: |
          cd apps/${{ github.event.inputs.app }}/ios
          echo "${{ secrets.PRIVATE_KEY }}" | base64 --decode > AuthKey.p8

      - name: Set up certificate file
        run: |
          cd apps/${{ github.event.inputs.app }}/ios
          echo "${{ secrets.CERTIFICATE_DISTRIBUTION_P12 }}" | base64 --decode > cert.p12

      - name: Initialize KeyChain
        run: |
          keychain initialize
      
      - name: Fetch Profiles
        run: |
          cd apps/${{ github.event.inputs.app }}/ios
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
          --platform IOS \
          --type IOS_APP_STORE \
          --certificate-key=@file:cert.p12 \
          --issuer-id ${{ secrets.ISSUER_ID }} \
          --key-id ${{ secrets.KEY_ID }} \
          --private-key=@file:AuthKey.p8 \
          --certificate-key-password ${{ secrets.CERT_PASSWORD }}

      - name: Add certificates
        run: |
          keychain add-certificates

      - name: Use profiles
        run: |
          xcode-project use-profiles

      - name: Install flutter deps
        run: |
          cd apps/${{ github.event.inputs.app }}
          flutter packages pub get

      - name: Run pod install if exists
        run: |
          find . -name "Podfile" -execdir pod install \;

      - name: Build ipa
        run: |
          cd apps/${{ github.event.inputs.app }}
          flutter build ipa --release \
          --export-options-plist=$HOME/export_options.plist

      - name: Publish ipa
        run: |
          app-store-connect publish \
          --path $(find $(pwd) -name "*.ipa")