name: Distribute iOS .ipa
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment"
        required: true
        default: release
        type: choice
        options:
          - release
          - beta

jobs:
  Build-And-Distribute-iOS:
    runs-on: macos-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Get current build_number
        id: build_number
        run: echo "build_number=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 'Create application.config file'
        run: |
          touch flutter_application/assets/config/application.config
          cd flutter_application/assets/config/
          echo API_ENDPOINT="${{ secrets.ENDPOINT }}" >> application.config
          echo API_KEY=${{ secrets.API_KEY }} >> application.config
          cat application.config

      - name: Install Flutter SDK
        uses: mobiledevops/flutter-sdk-action@v1.0.0
        with:
          flutter-sdk-version: 3.24.3
      - run: cd flutter_application && flutter pub get && flutter build ios --release --no-codesign

      - name: Export Signed IPA
        run: |
          cd flutter_application

          xcodebuild \
          -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration AppStoreDistribution archive \
          -archivePath build/Runner.xcarchive \
          clean archive \
          -allowProvisioningUpdates \
          MARKETING_VERSION=1.0.0 \
          CURRENT_PROJECT_VERSION=${{ steps.set_date.outputs.build_number }}

          xcodebuild \
          -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportOptionsPlist ios/exportOptions.plist \
          -exportPath build/Runner.ipa

      - name: Upload to TestFlight
        env:
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
        run: |
          cd flutter_application

          xcrun altool --upload-app -f build/Runner.ipa \
          --type ios \
          --apiKey $APP_STORE_CONNECT_KEY_ID \
          --apiIssuer $APP_STORE_CONNECT_ISSUER_ID